/// <reference path="../main.ts" />
/// <reference path="./ViewBase.ts" />

namespace BlackCat {
	export class AreaView extends ViewBase {

		static areaInfo = [
			{ "area": "中国", "areacode": "86", "codename": "CN" },
			{ "area": "安道尔", "areacode": "376", "codename": "AD" },
			{ "area": "阿拉伯联合酋长国", "areacode": "971", "codename": "AE" },
			{ "area": "阿富汗", "areacode": "93", "codename": "AF" },
			{ "area": "安提瓜和巴布达", "areacode": "1268", "codename": "AG" },
			{ "area": "安圭拉", "areacode": "1264", "codename": "AI" },
			{ "area": "阿尔巴尼亚", "areacode": "355", "codename": "AL" },
			{ "area": "亚美尼亚", "areacode": "374", "codename": "AM" },
			{ "area": "安哥拉", "areacode": "244", "codename": "AO" },
			{ "area": "阿根廷", "areacode": "54", "codename": "AR" },
			{ "area": "美属萨摩亚", "areacode": "1684", "codename": "AS" },
			{ "area": "奥地利", "areacode": "43", "codename": "AT" },
			{ "area": "澳大利亚", "areacode": "61", "codename": "AU" },
			{ "area": "阿鲁巴", "areacode": "297", "codename": "AW" },
			{ "area": "阿塞拜疆", "areacode": "994", "codename": "AZ" },
			{ "area": "波斯尼亚和黑塞哥维那", "areacode": "387", "codename": "BA" },
			{ "area": "巴巴多斯", "areacode": "1246", "codename": "BB" },
			{ "area": "孟加拉国", "areacode": "880", "codename": "BD" },
			{ "area": "比利时", "areacode": "32", "codename": "BE" },
			{ "area": "布基纳法索", "areacode": "226", "codename": "BF" },
			{ "area": "保加利亚", "areacode": "359", "codename": "BG" },
			{ "area": "巴林", "areacode": "973", "codename": "BH" },
			{ "area": "布隆迪", "areacode": "257", "codename": "BI" },
			{ "area": "贝宁", "areacode": "229", "codename": "BJ" },
			{ "area": "百慕大群岛", "areacode": "1441", "codename": "BM" },
			{ "area": "文莱", "areacode": "673", "codename": "BN" },
			{ "area": "玻利维亚", "areacode": "591", "codename": "BO" },
			{ "area": "荷兰加勒比", "areacode": "599", "codename": "BQ" },
			{ "area": "巴西", "areacode": "55", "codename": "BR" },
			{ "area": "巴哈马", "areacode": "1242", "codename": "BS" },
			{ "area": "不丹", "areacode": "975", "codename": "BT" },
			{ "area": "博茨瓦纳", "areacode": "267", "codename": "BW" },
			{ "area": "白俄罗斯", "areacode": "375", "codename": "BY" },
			{ "area": "伯利兹", "areacode": "501", "codename": "BZ" },
			{ "area": "加拿大", "areacode": "1", "codename": "CA" },
			{ "area": "刚果民主共和国", "areacode": "243", "codename": "CD" },
			{ "area": "中非共和国", "areacode": "236", "codename": "CF" },
			{ "area": "刚果共和国", "areacode": "242", "codename": "CG" },
			{ "area": "瑞士", "areacode": "41", "codename": "CH" },
			{ "area": "象牙海岸", "areacode": "225", "codename": "CI" },
			{ "area": "库克群岛", "areacode": "682", "codename": "CK" },
			{ "area": "智利", "areacode": "56", "codename": "CL" },
			{ "area": "喀麦隆", "areacode": "237", "codename": "CM" },
			{ "area": "哥伦比亚", "areacode": "57", "codename": "CO" },
			{ "area": "哥斯达黎加", "areacode": "506", "codename": "CR" },
			{ "area": "古巴", "areacode": "53", "codename": "CU" },
			{ "area": "开普", "areacode": "238", "codename": "CV" },
			{ "area": "库拉索", "areacode": "599", "codename": "CW" },
			{ "area": "塞浦路斯", "areacode": "357", "codename": "CY" },
			{ "area": "捷克", "areacode": "420", "codename": "CZ" },
			{ "area": "德国", "areacode": "49", "codename": "DE" },
			{ "area": "吉布提", "areacode": "253", "codename": "DJ" },
			{ "area": "丹麦", "areacode": "45", "codename": "DK" },
			{ "area": "多米尼加", "areacode": "1767", "codename": "DM" },
			{ "area": "多米尼加共和国", "areacode": "1809", "codename": "DO" },
			{ "area": "阿尔及利亚", "areacode": "213", "codename": "DZ" },
			{ "area": "厄瓜多尔", "areacode": "593", "codename": "EC" },
			{ "area": "爱沙尼亚", "areacode": "372", "codename": "EE" },
			{ "area": "埃及", "areacode": "20", "codename": "EG" },
			{ "area": "厄立特里亚", "areacode": "291", "codename": "ER" },
			{ "area": "西班牙", "areacode": "34", "codename": "ES" },
			{ "area": "埃塞俄比亚", "areacode": "251", "codename": "ET" },
			{ "area": "芬兰", "areacode": "358", "codename": "FI" },
			{ "area": "斐济", "areacode": "679", "codename": "FJ" },
			{ "area": "密克罗尼西亚", "areacode": "691", "codename": "FM" },
			{ "area": "法罗群岛", "areacode": "298", "codename": "FO" },
			{ "area": "法国", "areacode": "33", "codename": "FR" },
			{ "area": "加蓬", "areacode": "241", "codename": "GA" },
			{ "area": "英国", "areacode": "44", "codename": "GB" },
			{ "area": "格林纳达", "areacode": "1473", "codename": "GD" },
			{ "area": "格鲁吉亚", "areacode": "995", "codename": "GE" },
			{ "area": "法属圭亚那", "areacode": "594", "codename": "GF" },
			{ "area": "加纳", "areacode": "233", "codename": "GH" },
			{ "area": "直布罗陀", "areacode": "350", "codename": "GI" },
			{ "area": "格陵兰岛", "areacode": "299", "codename": "GL" },
			{ "area": "冈比亚", "areacode": "220", "codename": "GM" },
			{ "area": "几内亚", "areacode": "224", "codename": "GN" },
			{ "area": "瓜德罗普岛", "areacode": "590", "codename": "GP" },
			{ "area": "赤道几内亚", "areacode": "240", "codename": "GQ" },
			{ "area": "希腊", "areacode": "30", "codename": "GR" },
			{ "area": "瓜地马拉", "areacode": "502", "codename": "GT" },
			{ "area": "关岛", "areacode": "1671", "codename": "GU" },
			{ "area": "几内亚比绍共和国", "areacode": "245", "codename": "GW" },
			{ "area": "圭亚那", "areacode": "592", "codename": "GY" },
			{ "area": "中国香港", "areacode": "852", "codename": "HK" },
			{ "area": "洪都拉斯", "areacode": "504", "codename": "HN" },
			{ "area": "克罗地亚", "areacode": "385", "codename": "HR" },
			{ "area": "海地", "areacode": "509", "codename": "HT" },
			{ "area": "匈牙利", "areacode": "36", "codename": "HU" },
			{ "area": "印度尼西亚", "areacode": "62", "codename": "ID" },
			{ "area": "爱尔兰", "areacode": "353", "codename": "IE" },
			{ "area": "以色列", "areacode": "972", "codename": "IL" },
			{ "area": "印度", "areacode": "91", "codename": "IN" },
			{ "area": "伊拉克", "areacode": "964", "codename": "IQ" },
			{ "area": "伊朗", "areacode": "98", "codename": "IR" },
			{ "area": "冰岛", "areacode": "354", "codename": "IS" },
			{ "area": "意大利", "areacode": "39", "codename": "IT" },
			{ "area": "牙买加", "areacode": "1876", "codename": "JM" },
			{ "area": "约旦", "areacode": "962", "codename": "JO" },
			{ "area": "日本", "areacode": "81", "codename": "JP" },
			{ "area": "肯尼亚", "areacode": "254", "codename": "KE" },
			{ "area": "吉尔吉斯斯坦", "areacode": "996", "codename": "KG" },
			{ "area": "柬埔寨", "areacode": "855", "codename": "KH" },
			{ "area": "基里巴斯", "areacode": "686", "codename": "KI" },
			{ "area": "科摩罗", "areacode": "269", "codename": "KM" },
			{ "area": "圣基茨和尼维斯", "areacode": "1869", "codename": "KN" },
			{ "area": "朝鲜", "areacode": "850", "codename": "KP" },
			{ "area": "韩国", "areacode": "82", "codename": "KR" },
			{ "area": "科威特", "areacode": "965", "codename": "KW" },
			{ "area": "开曼群岛", "areacode": "1345", "codename": "KY" },
			{ "area": "哈萨克斯坦", "areacode": "7", "codename": "KZ" },
			{ "area": "老挝", "areacode": "856", "codename": "LA" },
			{ "area": "黎巴嫩", "areacode": "961", "codename": "LB" },
			{ "area": "圣露西亚", "areacode": "1758", "codename": "LC" },
			{ "area": "列支敦士登", "areacode": "423", "codename": "LI" },
			{ "area": "斯里兰卡", "areacode": "94", "codename": "LK" },
			{ "area": "利比里亚", "areacode": "231", "codename": "LR" },
			{ "area": "莱索托", "areacode": "266", "codename": "LS" },
			{ "area": "立陶宛", "areacode": "370", "codename": "LT" },
			{ "area": "卢森堡", "areacode": "352", "codename": "LU" },
			{ "area": "拉脱维亚", "areacode": "371", "codename": "LV" },
			{ "area": "利比亚", "areacode": "218", "codename": "LY" },
			{ "area": "摩洛哥", "areacode": "212", "codename": "MA" },
			{ "area": "摩纳哥", "areacode": "377", "codename": "MC" },
			{ "area": "摩尔多瓦", "areacode": "373", "codename": "MD" },
			{ "area": "黑山", "areacode": "382", "codename": "ME" },
			{ "area": "马达加斯加", "areacode": "261", "codename": "MG" },
			{ "area": "马绍尔群岛", "areacode": "692", "codename": "MH" },
			{ "area": "马其顿", "areacode": "389", "codename": "MK" },
			{ "area": "马里", "areacode": "223", "codename": "ML" },
			{ "area": "缅甸", "areacode": "95", "codename": "MM" },
			{ "area": "蒙古", "areacode": "976", "codename": "MN" },
			{ "area": "中国澳门", "areacode": "853", "codename": "MO" },
			{ "area": "毛里塔尼亚", "areacode": "222", "codename": "MR" },
			{ "area": "蒙特塞拉特岛", "areacode": "1664", "codename": "MS" },
			{ "area": "马耳他", "areacode": "356", "codename": "MT" },
			{ "area": "毛里求斯", "areacode": "230", "codename": "MU" },
			{ "area": "马尔代夫", "areacode": "960", "codename": "MV" },
			{ "area": "马拉维", "areacode": "265", "codename": "MW" },
			{ "area": "墨西哥", "areacode": "52", "codename": "MX" },
			{ "area": "马来西亚", "areacode": "60", "codename": "MY" },
			{ "area": "莫桑比克", "areacode": "258", "codename": "MZ" },
			{ "area": "纳米比亚", "areacode": "264", "codename": "NA" },
			{ "area": "新喀里多尼亚", "areacode": "687", "codename": "NC" },
			{ "area": "尼日尔", "areacode": "227", "codename": "NE" },
			{ "area": "尼日利亚", "areacode": "234", "codename": "NG" },
			{ "area": "尼加拉瓜", "areacode": "505", "codename": "NI" },
			{ "area": "荷兰", "areacode": "31", "codename": "NL" },
			{ "area": "挪威", "areacode": "47", "codename": "NO" },
			{ "area": "尼泊尔", "areacode": "977", "codename": "NP" },
			{ "area": "拿鲁岛", "areacode": "674", "codename": "NR" },
			{ "area": "新西兰", "areacode": "64", "codename": "NZ" },
			{ "area": "阿曼", "areacode": "968", "codename": "OM" },
			{ "area": "巴拿马", "areacode": "507", "codename": "PA" },
			{ "area": "秘鲁", "areacode": "51", "codename": "PE" },
			{ "area": "法属波利尼西亚", "areacode": "689", "codename": "PF" },
			{ "area": "巴布亚新几内亚", "areacode": "675", "codename": "PG" },
			{ "area": "菲律宾", "areacode": "63", "codename": "PH" },
			{ "area": "巴基斯坦", "areacode": "92", "codename": "PK" },
			{ "area": "波兰", "areacode": "48", "codename": "PL" },
			{ "area": "圣彼埃尔和密克隆岛", "areacode": "508", "codename": "PM" },
			{ "area": "波多黎各", "areacode": "1787", "codename": "PR" },
			{ "area": "葡萄牙", "areacode": "351", "codename": "PT" },
			{ "area": "帕劳", "areacode": "680", "codename": "PW" },
			{ "area": "巴拉圭", "areacode": "595", "codename": "PY" },
			{ "area": "卡塔尔", "areacode": "974", "codename": "QA" },
			{ "area": "留尼汪", "areacode": "262", "codename": "RE" },
			{ "area": "罗马尼亚", "areacode": "40", "codename": "RO" },
			{ "area": "塞尔维亚", "areacode": "381", "codename": "RS" },
			{ "area": "俄罗斯", "areacode": "7", "codename": "RU" },
			{ "area": "卢旺达", "areacode": "250", "codename": "RW" },
			{ "area": "沙特阿拉伯", "areacode": "966", "codename": "SA" },
			{ "area": "所罗门群岛", "areacode": "677", "codename": "SB" },
			{ "area": "塞舌尔", "areacode": "248", "codename": "SC" },
			{ "area": "苏丹", "areacode": "249", "codename": "SD" },
			{ "area": "瑞典", "areacode": "46", "codename": "SE" },
			{ "area": "新加坡", "areacode": "65", "codename": "SG" },
			{ "area": "斯洛文尼亚", "areacode": "386", "codename": "SI" },
			{ "area": "斯洛伐克", "areacode": "421", "codename": "SK" },
			{ "area": "塞拉利昂", "areacode": "232", "codename": "SL" },
			{ "area": "圣马力诺", "areacode": "378", "codename": "SM" },
			{ "area": "塞内加尔", "areacode": "221", "codename": "SN" },
			{ "area": "索马里", "areacode": "252", "codename": "SO" },
			{ "area": "苏里南", "areacode": "597", "codename": "SR" },
			{ "area": "圣多美和普林西比", "areacode": "239", "codename": "ST" },
			{ "area": "萨尔瓦多", "areacode": "503", "codename": "SV" },
			{ "area": "叙利亚", "areacode": "963", "codename": "SY" },
			{ "area": "斯威士兰", "areacode": "268", "codename": "SZ" },
			{ "area": "特克斯和凯科斯群岛", "areacode": "1649", "codename": "TC" },
			{ "area": "乍得", "areacode": "235", "codename": "TD" },
			{ "area": "多哥", "areacode": "228", "codename": "TG" },
			{ "area": "泰国", "areacode": "66", "codename": "TH" },
			{ "area": "塔吉克斯坦", "areacode": "992", "codename": "TJ" },
			{ "area": "东帝汶", "areacode": "670", "codename": "TL" },
			{ "area": "土库曼斯坦", "areacode": "993", "codename": "TM" },
			{ "area": "突尼斯", "areacode": "216", "codename": "TN" },
			{ "area": "汤加", "areacode": "676", "codename": "TO" },
			{ "area": "土耳其", "areacode": "90", "codename": "TR" },
			{ "area": "特立尼达和多巴哥", "areacode": "1868", "codename": "TT" },
			{ "area": "中国台湾", "areacode": "886", "codename": "TW" },
			{ "area": "坦桑尼亚", "areacode": "255", "codename": "TZ" },
			{ "area": "乌克兰", "areacode": "380", "codename": "UA" },
			{ "area": "乌干达", "areacode": "256", "codename": "UG" },
			{ "area": "美国", "areacode": "1", "codename": "US" },
			{ "area": "乌拉圭", "areacode": "598", "codename": "UY" },
			{ "area": "乌兹别克斯坦", "areacode": "998", "codename": "UZ" },
			{ "area": "圣文森特和格林纳丁斯", "areacode": "1784", "codename": "VC" },
			{ "area": "委内瑞拉", "areacode": "58", "codename": "VE" },
			{ "area": "英属处女群岛", "areacode": "1284", "codename": "VG" },
			{ "area": "越南", "areacode": "84", "codename": "VN" },
			{ "area": "瓦努阿图", "areacode": "678", "codename": "VU" },
			{ "area": "萨摩亚", "areacode": "685", "codename": "WS" },
			{ "area": "也门", "areacode": "967", "codename": "YE" },
			{ "area": "马约特", "areacode": "269", "codename": "YT" },
			{ "area": "南非", "areacode": "27", "codename": "ZA" },
			{ "area": "赞比亚", "areacode": "260", "codename": "ZM" },
			{ "area": "津巴布韦", "areacode": "263", "codename": "ZW" }

		]

		static getByAreaCode(areaCode: string) {
			var areaInfo = null;
			AreaView.areaInfo.forEach(
				area => {
					if (area.areacode == areaCode) {
						areaInfo = area;
					}
				}
			)
			return areaInfo;
		}

		static getByCodeName(codeName: string) {
			var areaInfo = null;
			AreaView.areaInfo.forEach(
				area => {
					if (area.codename == codeName) {
						areaInfo = area;
					}
				}
			)
			return areaInfo;
		}
	}
}